[package]
name = "hid-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "^0.4"
env_logger = "^0.11"
evdev = "0.13.1"
log = "^0.4"
nix = { version = "^0.29", features = ["poll"] }
